import { Status } from '@prisma/client'
import { Badge } from '@radix-ui/themes'
import React from 'react'

//use Record to decalre a key value map with their type.
//Type Status is generated by the prisma client. You can use the type directly from the prisma client. 
//Prisma client generated the type from our model in the schema.prisma
const statusMap: Record<Status, { label: string, color: 'red' | 'violet' | 'green' }> = {
    OPEN: { label: 'Opened', color: 'red' },
    IN_PROGRESS: { label: 'In Progress', color: 'violet' },
    CLOSED: { label: 'Closed', color: 'green' },    
}
const IssueStatusBadge = ({status}:{status:Status}) => {
  return (
    <Badge color={statusMap[status].color}>
        {statusMap[status].label}
    </Badge>
  )
}

export default IssueStatusBadge
